### ISSUE TITLE
Lazy.Take should return lazy array instead of actual sequence

### ISSUE THREAD

**Issue by allenbrubaker** [dtao/lazy.js#137] opened 2015-01-14 18:05 UTC
Shouldn't Lazy(...).take(1) return a lazy array rather than the actual array.  What if I wanted to do Lazy(..).take(1).map().filter()....toArray()?  What is the recommended way to go about doing this?

**Comment by djcsdy** [comment] 2015-01-15 14:09
`take()` does return a lazy sequence :)

```js
Lazy([1, 2, 3])
    .take(1)
    .map(function(n) { return n * 10; })
    .toArray();
// -> [10]
```

Here `2` and `3` are never evaluated.

**Comment by dtao** [comment] 2015-08-30 18:01
As @djcsdy says, `take()` already does return a lazy sequence, thus I'm closing this.

Are you referring to the fact that `take()` (without an argument) returns the first value eagerly? That's by design. If you just want 1 element you can pass in 1 and you'll get a sequence back.

Let me know if I'm misunderstanding the issue, in which case I'll be happy to reopen.

**Closed by dtao** 2015-08-30 18:01 UTC
